PACKAGE_NAME=openvfd
PACKAGE_VERSION=8fadd10
AUTOINSTALL=yes
CLEAN="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build clean"
MAKE="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build modules V=1 VV=1"
BUILT_MODULE_NAME="openvfd"
BUILT_MODULE_LOCATION="."
DEST_MODULE_LOCATION="/updates/dkms"
# POST_INSTALL="/bin/sh post_install.sh"
