# INSTALL:
##sudo dkms remove -m ea6621q -v 1.0
#sudo dkms add -m ea6621q -v 1.0
#sudo dkms build -m ea6621q -v 1.0
#sudo dkms install -m ea6621q -v 1.0



PACKAGE_VARIANT="sdio"
PACKAGE_NAME="ea6621q"
PACKAGE_VERSION="1.0"
AUTOINSTALL=yes

CLEAN="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build clean"
MAKE="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build modules"

BUILT_MODULE_NAME[0]="skw_sdio"
DEST_MODULE_NAME[0]="skw_sdio"
BUILT_MODULE_LOCATION[0]="drivers/net/wireless/ea6621q/seekwaveplatform/sdio"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="skw_bootcoms"
DEST_MODULE_NAME[1]="skw_bootcoms"
BUILT_MODULE_LOCATION[1]="drivers/net/wireless/ea6621q/seekwaveplatform/skwutil"
DEST_MODULE_LOCATION[1]="/updates/dkms"

BUILT_MODULE_NAME[2]="skw"
DEST_MODULE_NAME[2]="skw"
BUILT_MODULE_LOCATION[2]="drivers/net/wireless/ea6621q/skwifi"
DEST_MODULE_LOCATION[2]="/updates/dkms"

BUILT_MODULE_NAME[3]="skwbt"
DEST_MODULE_NAME[3]="skwbt"
BUILT_MODULE_LOCATION[3]="drivers/net/wireless/ea6621q/swtbt4l"
DEST_MODULE_LOCATION[3]="/updates/dkms"
